### ISSUE TITLE
clicking options works only sporadically in Chrome on OS X

### ISSUE THREAD

**Issue by clj** [tcrosen/twitter-bootstrap-typeahead#11]
Hi,

Selecting an option in the typeahead dropdown works only sporadically in Chrome on OS X.  I suspect that this is related to the following (identical) issue in the official Twitter Bootstrap repository, which also contains a fix: https://github.com/twitter/bootstrap/issues/4018

**Comment by tcrosen** [comment]
Fixed as per [#2715](https://github.com/thbar/bootstrap/commit/92189b87ad9e1f46966d5d730e3d8f99f969d92c)

**Comment by tomvo** [comment]
Problem still exists on Mountain Lion and Chrome Version 21.0.1180.89 (MBP i7 with 16gb ram), will file bug with bootstrap too. Changing the delay in the fix to 250ms seems to fix this problem. 
It's a timing problem related to hiding the result list before the click event is fired.
